# Generated by Django 6.0 on 2026-01-05 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=8, max_digits=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cripto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='catalogo.criptos')),
            ],
        ),
    ]
